
using System;
using System.Collections.ObjectModel;
namespace Sourcemod
{
	public partial class SourceMod
	{

public const object SOURCEMOD_V_TAG		""
public const object SOURCEMOD_V_CSET	"0caa349f"
public const object SOURCEMOD_V_MAJOR	1
public const object SOURCEMOD_V_MINOR	11
public const object SOURCEMOD_V_RELEASE	0
public const object SOURCEMOD_V_REV		6645

public const object SOURCEMOD_VERSION	"1.11.0.6645"
    	}
}